export {
  SkeletonBox,
  SkeletonText,
  SkeletonAvatar,
  SkeletonButton,
  SkeletonInput,
  SkeletonPill,
  SkeletonCard,
  SkeletonKPI,
  SkeletonHero,
  SkeletonTableRow,
  SkeletonListRow,
} from "./primitives";

export {
  DashboardSkeleton,
  JobsSkeleton,
  JobDetailsSkeleton,
  CandidatesSkeleton,
  CandidateReportSkeleton,
  InterviewsSkeleton,
  InterviewDetailsSkeleton,
  MyScheduleSkeleton,
  AssessmentsSkeleton,
  AssessmentDetailsSkeleton,
  AssessmentCandidateReportSkeleton,
  AssessmentDriveSkeleton,
  QuestionPoolSkeleton,
  QuestionEditorSkeleton,
  ReportsSkeleton,
  SettingsSkeleton,
  EnterprisesSkeleton,
  EnterpriseDetailsSkeleton,
  LoginSignupSkeleton,
} from "./pages";
