import type { AssessmentFormDraft, AssessmentRecord } from "./types";
import { DEFAULT_GUIDELINES_TEXT } from "./types";

const BASE_CONFIG: AssessmentFormDraft = {
  name: "",
  durationMinutes: 60,
  durationIsCustom: false,
  validityDays: 7,
  qualifyingPercentage: 70,
  partialScoring: false,
  partialScoringAppliesTo: { mcq: false, comprehension: false },
  negativeMarking: false,
  negativeMarkingAppliesTo: { mcq: false, comprehension: false },
  negativePenaltyPercent: 25,
  role: "React Developer",
  difficulty: "Intermediate",
  tags: ["Frontend"],
  languages: ["TypeScript", "JavaScript"],
  selectedQuestions: [],
  guidelines: DEFAULT_GUIDELINES_TEXT,
};

export const SEED_ASSESSMENTS: AssessmentRecord[] = [
  {
    id: "asm-frontend-react",
    name: "Frontend Developer Assessment",
    role: "React Developer",
    createdBy: "Marcus Chen",
    createdOn: "May 18, 2026",
    invited: 120,
    notStarted: 38,
    evaluated: 64,
    qualified: 22,
    status: "Ongoing",
    enabled: true,
    shareLink: "https://hire.zecode.io/a/frontend-react-2026",
    config: {
      ...BASE_CONFIG,
      name: "Frontend Developer Assessment",
      role: "React Developer",
      durationMinutes: 90,
      qualifyingPercentage: 72,
    },
  },
  {
    id: "asm-backend-core",
    name: "Backend Systems — Core",
    role: "Backend Engineer",
    createdBy: "Alex Rivera",
    createdOn: "May 09, 2026",
    invited: 44,
    notStarted: 12,
    evaluated: 18,
    qualified: 9,
    status: "Ongoing",
    enabled: true,
    shareLink: "https://hire.zecode.io/a/backend-core",
    config: {
      ...BASE_CONFIG,
      name: "Backend Systems — Core",
      role: "Backend Engineer",
      languages: ["Python", "Go"],
      difficulty: "Advanced",
    },
  },
  {
    id: "asm-sql-analytics",
    name: "SQL + Analytics",
    role: "Data Analyst",
    createdBy: "Jordan Lee",
    createdOn: "May 06, 2026",
    invited: 30,
    notStarted: 6,
    evaluated: 19,
    qualified: 11,
    status: "Completed",
    enabled: false,
    shareLink: "https://hire.zecode.io/a/sql-analytics",
    config: {
      ...BASE_CONFIG,
      name: "SQL + Analytics",
      role: "Data Analyst",
      languages: ["SQL"],
    },
  },
  {
    id: "asm-system-design",
    name: "System Design — Senior",
    role: "Platform Engineer",
    createdBy: "Marcus Chen",
    createdOn: "May 03, 2026",
    invited: 18,
    notStarted: 4,
    evaluated: 10,
    qualified: 5,
    status: "Completed",
    enabled: true,
    shareLink: "https://hire.zecode.io/a/system-design-senior",
    config: {
      ...BASE_CONFIG,
      name: "System Design — Senior",
      role: "Platform Engineer",
      difficulty: "Expert",
      durationMinutes: 120,
    },
  },
  {
    id: "asm-fullstack",
    name: "Full Stack Practical",
    role: "Full Stack Engineer",
    createdBy: "Elena Hoffmann",
    createdOn: "May 15, 2026",
    invited: 56,
    notStarted: 22,
    evaluated: 28,
    qualified: 14,
    status: "Ongoing",
    enabled: true,
    shareLink: "https://hire.zecode.io/a/fullstack-practical",
    config: {
      ...BASE_CONFIG,
      name: "Full Stack Practical",
      role: "Full Stack Engineer",
    },
  },
  {
    id: "asm-devops-draft",
    name: "DevOps Foundations",
    role: "DevOps Engineer",
    createdBy: "Marcus Chen",
    createdOn: "May 20, 2026",
    invited: 0,
    notStarted: 0,
    evaluated: 0,
    qualified: 0,
    status: "Draft",
    enabled: false,
    shareLink: "https://hire.zecode.io/a/devops-foundations",
    config: {
      ...BASE_CONFIG,
      name: "DevOps Foundations",
      role: "DevOps Engineer",
    },
  },
];
