import type {
  AssessmentScheduleRecord,
  AssessmentScheduleTab,
  LiveAssessmentAttempt,
  ScheduleAttemptStatus,
  ScheduleCalendarEvent,
  ScheduleInsight,
} from "./scheduleTypes";

const RECRUITERS = ["Marcus Chen", "Alex Rivera", "Priya Nair", "Jordan Lee"];

function row(
  partial: Omit<AssessmentScheduleRecord, "recruiter"> & { recruiter?: string },
): AssessmentScheduleRecord {
  return { recruiter: RECRUITERS[Math.floor(Math.random() * RECRUITERS.length)], ...partial };
}

export const SEED_SCHEDULES: AssessmentScheduleRecord[] = [
  row({
    id: "sch-1",
    tab: "upcoming",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-1",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    linkedin: "linkedin.com/in/priyasharma",
    resumeUrl: "/resumes/demo.pdf",
    inviteSentAt: "May 18, 2026",
    expiryDate: "May 25, 2026",
    attemptWindow: "May 18 – May 25",
    calendarDate: "2026-05-20",
    status: "Not Started",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 1,
    lastReminderAt: "6h ago",
    reminderLevel: "active",
  }),
  row({
    id: "sch-2",
    tab: "upcoming",
    assessmentId: "asm-backend-core",
    assessmentName: "Backend Systems — Core",
    role: "Backend Engineer",
    durationMinutes: 120,
    candidateId: "ac-asm-backend-core-2",
    name: "James Okonkwo",
    email: "j.okonkwo@corp.io",
    linkedin: "linkedin.com/in/jokonkwo",
    inviteSentAt: "May 19, 2026",
    expiryDate: "May 20, 2026",
    attemptWindow: "May 19 – May 20",
    calendarDate: "2026-05-20",
    status: "Not Started",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 2,
    lastReminderAt: "3h ago",
    reminderLevel: "escalated",
  }),
  row({
    id: "sch-3",
    tab: "upcoming",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-3",
    name: "Elena Vasquez",
    email: "elena.v@studio.dev",
    inviteSentAt: "May 17, 2026",
    expiryDate: "May 24, 2026",
    attemptWindow: "May 17 – May 24",
    calendarDate: "2026-05-21",
    status: "Started",
    progress: 8,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 0,
    lastReminderAt: null,
    reminderLevel: "muted",
  }),
  row({
    id: "sch-4",
    tab: "ongoing",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-4",
    name: "Marcus Webb",
    email: "marcus.webb@hire.co",
    linkedin: "linkedin.com/in/marcuswebb",
    resumeUrl: "/resumes/demo.pdf",
    inviteSentAt: "May 15, 2026",
    expiryDate: "May 22, 2026",
    attemptWindow: "May 15 – May 22",
    calendarDate: "2026-05-20",
    status: "Ongoing",
    progress: 54,
    score: null,
    qualified: null,
    malpracticeSignals: ["Tab switch"],
    remindersSent: 1,
    lastReminderAt: "12h ago",
    reminderLevel: "active",
  }),
  row({
    id: "sch-5",
    tab: "ongoing",
    assessmentId: "asm-backend-core",
    assessmentName: "Backend Systems — Core",
    role: "Backend Engineer",
    durationMinutes: 120,
    candidateId: "ac-asm-backend-core-1",
    name: "Aisha Khan",
    email: "aisha.khan@mail.com",
    inviteSentAt: "May 14, 2026",
    expiryDate: "May 21, 2026",
    attemptWindow: "May 14 – May 21",
    calendarDate: "2026-05-20",
    status: "Ongoing",
    progress: 72,
    score: null,
    qualified: null,
    malpracticeSignals: ["Camera anomaly", "Tab switch"],
    remindersSent: 0,
    lastReminderAt: null,
    reminderLevel: "muted",
  }),
  row({
    id: "sch-6",
    tab: "ongoing",
    assessmentId: "asm-sql-analytics",
    assessmentName: "SQL & Analytics Screening",
    role: "Data Analyst",
    durationMinutes: 60,
    candidateId: "ac-asm-sql-analytics-2",
    name: "Noah Fischer",
    email: "noah.fischer@tech.de",
    linkedin: "linkedin.com/in/noahfischer",
    resumeUrl: "/resumes/demo.pdf",
    inviteSentAt: "May 16, 2026",
    expiryDate: "May 23, 2026",
    attemptWindow: "May 16 – May 23",
    calendarDate: "2026-05-20",
    status: "Started",
    progress: 22,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 1,
    lastReminderAt: "1d ago",
    reminderLevel: "active",
  }),
  row({
    id: "sch-7",
    tab: "completed",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-2",
    name: "James Okonkwo",
    email: "j.okonkwo@corp.io",
    linkedin: "linkedin.com/in/jokonkwo",
    inviteSentAt: "May 10, 2026",
    expiryDate: "May 17, 2026",
    attemptWindow: "May 10 – May 17",
    calendarDate: "2026-05-18",
    status: "Evaluated",
    progress: 100,
    score: 84,
    qualified: true,
    malpracticeSignals: [],
    remindersSent: 2,
    lastReminderAt: "4d ago",
    reminderLevel: "muted",
  }),
  row({
    id: "sch-8",
    tab: "completed",
    assessmentId: "asm-backend-core",
    assessmentName: "Backend Systems — Core",
    role: "Backend Engineer",
    durationMinutes: 120,
    candidateId: "ac-asm-backend-core-3",
    name: "Sofia Lindström",
    email: "sofia.l@nordic.io",
    inviteSentAt: "May 08, 2026",
    expiryDate: "May 15, 2026",
    attemptWindow: "May 08 – May 15",
    calendarDate: "2026-05-16",
    status: "Submitted",
    progress: 100,
    score: 71,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 1,
    lastReminderAt: "5d ago",
    reminderLevel: "muted",
  }),
  row({
    id: "sch-9",
    tab: "completed",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-5",
    name: "Daniel Park",
    email: "daniel.park@startup.com",
    linkedin: "linkedin.com/in/danielpark",
    resumeUrl: "/resumes/demo.pdf",
    inviteSentAt: "May 06, 2026",
    expiryDate: "May 13, 2026",
    attemptWindow: "May 06 – May 13",
    calendarDate: "2026-05-14",
    status: "Evaluated",
    progress: 100,
    score: 62,
    qualified: false,
    malpracticeSignals: ["Copy attempt"],
    remindersSent: 3,
    lastReminderAt: "6d ago",
    reminderLevel: "muted",
  }),
  row({
    id: "sch-10",
    tab: "expired",
    assessmentId: "asm-sql-analytics",
    assessmentName: "SQL & Analytics Screening",
    role: "Data Analyst",
    durationMinutes: 60,
    candidateId: "ac-asm-sql-analytics-1",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@global.jp",
    inviteSentAt: "May 01, 2026",
    expiryDate: "May 08, 2026",
    attemptWindow: "May 01 – May 08",
    calendarDate: "2026-05-08",
    status: "Expired",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 2,
    lastReminderAt: "12d ago",
    reminderLevel: "muted",
  }),
  row({
    id: "sch-11",
    tab: "expired",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "ac-asm-frontend-react-6",
    name: "Olivia Grant",
    email: "olivia.grant@agency.com",
    linkedin: "linkedin.com/in/oliviagrant",
    inviteSentAt: "Apr 28, 2026",
    expiryDate: "May 05, 2026",
    attemptWindow: "Apr 28 – May 05",
    calendarDate: "2026-05-05",
    status: "Expired",
    progress: 18,
    score: null,
    qualified: null,
    malpracticeSignals: ["Tab switch"],
    remindersSent: 3,
    lastReminderAt: "15d ago",
    reminderLevel: "escalated",
  }),
  row({
    id: "sch-12",
    tab: "drafts",
    assessmentId: "asm-backend-core",
    assessmentName: "Backend Systems — Core",
    role: "Backend Engineer",
    durationMinutes: 120,
    candidateId: "draft-cand-1",
    name: "Ravi Menon",
    email: "ravi.menon@dev.in",
    inviteSentAt: "—",
    expiryDate: "May 27, 2026",
    attemptWindow: "Not scheduled",
    calendarDate: "2026-05-22",
    status: "Not Started",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 0,
    lastReminderAt: null,
    reminderLevel: "muted",
    isDraft: true,
  }),
  row({
    id: "sch-13",
    tab: "drafts",
    assessmentId: "asm-frontend-react",
    assessmentName: "Frontend Developer Assessment",
    role: "React Developer",
    durationMinutes: 90,
    candidateId: "draft-cand-2",
    name: "Chloe Bennett",
    email: "chloe.b@design.io",
    linkedin: "linkedin.com/in/chloebennett",
    inviteSentAt: "—",
    expiryDate: "May 30, 2026",
    attemptWindow: "Not scheduled",
    calendarDate: "2026-05-23",
    status: "Not Started",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 0,
    lastReminderAt: null,
    reminderLevel: "muted",
    isDraft: true,
  }),
  row({
    id: "sch-14",
    tab: "upcoming",
    assessmentId: "asm-sql-analytics",
    assessmentName: "SQL & Analytics Screening",
    role: "Data Analyst",
    durationMinutes: 60,
    candidateId: "ac-asm-sql-analytics-3",
    name: "Ravi Menon",
    email: "ravi.menon@dev.in",
    inviteSentAt: "May 19, 2026",
    expiryDate: "May 20, 2026",
    attemptWindow: "May 19 – May 20",
    calendarDate: "2026-05-20",
    status: "Not Started",
    progress: 0,
    score: null,
    qualified: null,
    malpracticeSignals: [],
    remindersSent: 1,
    lastReminderAt: "8h ago",
    reminderLevel: "active",
  }),
  row({
    id: "sch-15",
    tab: "completed",
    assessmentId: "asm-backend-core",
    assessmentName: "Backend Systems — Core",
    role: "Backend Engineer",
    durationMinutes: 120,
    candidateId: "ac-asm-backend-core-4",
    name: "Chloe Bennett",
    email: "chloe.b@design.io",
    linkedin: "linkedin.com/in/chloebennett",
    resumeUrl: "/resumes/demo.pdf",
    inviteSentAt: "May 12, 2026",
    expiryDate: "May 19, 2026",
    attemptWindow: "May 12 – May 19",
    calendarDate: "2026-05-19",
    status: "Evaluated",
    progress: 100,
    score: 91,
    qualified: true,
    malpracticeSignals: [],
    remindersSent: 1,
    lastReminderAt: "2d ago",
    reminderLevel: "muted",
  }),
];

export const SEED_LIVE_ATTEMPTS: LiveAssessmentAttempt[] = [
  {
    id: "live-1",
    scheduleId: "sch-4",
    candidateName: "Marcus Webb",
    assessmentName: "Frontend Developer Assessment",
    currentQuestion: "Implement debounced search hook",
    remainingMinutes: 38,
    internetStability: "Stable",
    tabSwitchCount: 2,
    cameraStatus: "On",
    fullscreen: true,
  },
  {
    id: "live-2",
    scheduleId: "sch-5",
    candidateName: "Aisha Khan",
    assessmentName: "Backend Systems — Core",
    currentQuestion: "Design rate-limiter middleware",
    remainingMinutes: 52,
    internetStability: "Unstable",
    tabSwitchCount: 4,
    cameraStatus: "On",
    fullscreen: false,
  },
  {
    id: "live-3",
    scheduleId: "sch-6",
    candidateName: "Noah Fischer",
    assessmentName: "SQL & Analytics Screening",
    currentQuestion: "Window functions — cohort retention",
    remainingMinutes: 41,
    internetStability: "Stable",
    tabSwitchCount: 0,
    cameraStatus: "On",
    fullscreen: true,
  },
];

export function scheduleToCalendarKind(s: AssessmentScheduleRecord): ScheduleCalendarEvent["kind"] {
  if (s.malpracticeSignals.length > 0 && (s.tab === "ongoing" || s.tab === "completed")) return "malpractice";
  if (s.tab === "expired" || s.status === "Expired") return "expired";
  if (s.tab === "completed" || s.status === "Submitted" || s.status === "Evaluated") return "completed";
  if (s.tab === "ongoing" || s.status === "Ongoing" || s.status === "Started") return "ongoing";
  return "scheduled";
}

export function buildCalendarEvents(schedules: AssessmentScheduleRecord[]): ScheduleCalendarEvent[] {
  return schedules
    .filter((s) => !s.isDraft)
    .map((s, i) => ({
      id: `evt-${s.id}`,
      scheduleId: s.id,
      title: s.name,
      subtitle: s.assessmentName,
      date: s.calendarDate,
      startHour: 9 + (i % 6),
      durationHours: Math.max(1, Math.ceil(s.durationMinutes / 60)),
      kind: scheduleToCalendarKind(s),
      schedule: s,
    }));
}

export function computeScheduleInsights(schedules: AssessmentScheduleRecord[]): ScheduleInsight[] {
  const today = schedules.filter((s) => s.expiryDate.includes("May 20") && s.tab === "upcoming").length;
  const flagged = schedules.filter((s) => s.malpracticeSignals.length > 0).length;
  const pendingEval = schedules.filter((s) => s.status === "Submitted").length;
  const abandoned = schedules.filter((s) => s.progress > 0 && s.progress < 30 && s.tab === "ongoing").length;

  return [
    { id: "expire", label: `${today || 12} candidates expire today`, tone: "warning" },
    { id: "flagged", label: `${flagged || 3} candidates flagged`, tone: "danger" },
    { id: "eval", label: `${pendingEval || 5} evaluations pending`, tone: "default" },
    { id: "abandon", label: `${abandoned || 8} abandoned attempts`, tone: "warning" },
  ];
}

export function computeHeroMetrics(schedules: AssessmentScheduleRecord[]) {
  const todayStr = "May 20";
  return {
    scheduledToday: schedules.filter((s) => s.tab === "upcoming" && s.inviteSentAt.includes(todayStr)).length + 8,
    ongoingAttempts: schedules.filter((s) => s.tab === "ongoing").length,
    pendingEvaluations: schedules.filter((s) => s.status === "Submitted").length + 5,
    expiringToday: schedules.filter((s) => s.expiryDate.includes(todayStr)).length + 12,
    qualifiedCandidates: schedules.filter((s) => s.qualified === true).length + 18,
  };
}

export function tabForStatus(status: ScheduleAttemptStatus, isDraft?: boolean): AssessmentScheduleTab {
  if (isDraft) return "drafts";
  if (status === "Expired") return "expired";
  if (status === "Submitted" || status === "Evaluated") return "completed";
  if (status === "Ongoing" || status === "Started") return "ongoing";
  return "upcoming";
}
