import type { PoolQuestion, QuestionPoolCategory } from "./types";

export const QUESTION_POOL: PoolQuestion[] = [
  {
    id: "q-coding-2",
    title: "Implement LRU cache with O(1) operations",
    type: "Coding",
    difficulty: "Expert",
    estimatedMinutes: 45,
    tags: ["cache", "design"],
    skills: ["Data structures"],
    languages: ["Java", "C++", "Python"],
    defaultMarks: 20,
    defaultWeightage: 2,
  },
  {
    id: "q-db-1",
    title: "7-day retention by signup cohort",
    type: "Database",
    difficulty: "Medium",
    estimatedMinutes: 30,
    tags: ["sql", "analytics"],
    skills: ["SQL"],
    languages: ["SQL"],
    defaultMarks: 15,
    defaultWeightage: 1.5,
  },
  {
    id: "q-db-2",
    title: "Optimize slow hiring funnel query",
    type: "Database",
    difficulty: "Hard",
    estimatedMinutes: 35,
    tags: ["indexing", "performance"],
    skills: ["SQL", "Performance"],
    languages: ["SQL", "PostgreSQL"],
    defaultMarks: 15,
    defaultWeightage: 1.5,
  },
  {
    id: "q-mcq-1",
    title: "HTTP caching semantics",
    type: "MCQ",
    difficulty: "Easy",
    estimatedMinutes: 8,
    tags: ["web", "http"],
    skills: ["Networking"],
    languages: ["JavaScript"],
    defaultMarks: 5,
    defaultWeightage: 0.5,
  },
  {
    id: "q-mcq-2",
    title: "React reconciliation fundamentals",
    type: "MCQ",
    difficulty: "Medium",
    estimatedMinutes: 10,
    tags: ["react", "frontend"],
    skills: ["React"],
    languages: ["TypeScript", "JavaScript"],
    defaultMarks: 5,
    defaultWeightage: 0.5,
  },
  {
    id: "q-comp-1",
    title: "API rate limiting design brief",
    type: "Comprehension",
    difficulty: "Medium",
    estimatedMinutes: 15,
    tags: ["system-design"],
    skills: ["Architecture"],
    languages: [],
    defaultMarks: 10,
    defaultWeightage: 1,
  },
  {
    id: "q-open-1",
    title: "Describe a production incident you resolved",
    type: "Open Ended",
    difficulty: "Medium",
    estimatedMinutes: 12,
    tags: ["behavioral"],
    skills: ["Communication"],
    languages: [],
    defaultMarks: 10,
    defaultWeightage: 1,
  },
  {
    id: "q-fill-1",
    title: "Complete the async middleware snippet",
    type: "Fill in the Blanks",
    difficulty: "Easy",
    estimatedMinutes: 10,
    tags: ["nodejs"],
    skills: ["Backend"],
    languages: ["JavaScript", "TypeScript"],
    defaultMarks: 8,
    defaultWeightage: 0.8,
  },
  {
    id: "q-debug-1",
    title: "Fix race condition in debounced search",
    type: "Debug Snippet",
    difficulty: "Medium",
    estimatedMinutes: 20,
    tags: ["debugging", "react"],
    skills: ["Frontend"],
    languages: ["TypeScript", "JavaScript"],
    defaultMarks: 12,
    defaultWeightage: 1.2,
  },
  {
    id: "q-coding-3",
    title: "Binary tree vertical order traversal",
    type: "Coding",
    difficulty: "Medium",
    estimatedMinutes: 35,
    tags: ["trees"],
    skills: ["Algorithms"],
    languages: ["Python", "Java", "Go"],
    defaultMarks: 15,
    defaultWeightage: 1.5,
  },
  {
    id: "q-mcq-3",
    title: "TypeScript utility types",
    type: "MCQ",
    difficulty: "Hard",
    estimatedMinutes: 12,
    tags: ["typescript"],
    skills: ["TypeScript"],
    languages: ["TypeScript"],
    defaultMarks: 6,
    defaultWeightage: 0.6,
  },
];

export function getQuestionsByCategory(category: QuestionPoolCategory): PoolQuestion[] {
  return QUESTION_POOL.filter((q) => q.type === category);
}

export function getPoolQuestion(id: string): PoolQuestion | undefined {
  return QUESTION_POOL.find((q) => q.id === id);
}
