/** Central route paths — use instead of hardcoded strings in links and redirects. */
export const ROUTES = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  hiringJobs: "/hiring/jobs",
  hiringJobNew: "/hiring/jobs/new",
  hiringJob: (jobId: string) => `/hiring/jobs/${jobId}`,
  hiringJobInterview: (jobId: string) => `/hiring/jobs/${jobId}?mode=interview&tab=interviews`,
  jobs: "/jobs",
  job: (id: string) => `/jobs/${id}`,
  jobPipeline: (id: string) => `/jobs/${id}/pipeline`,
  jobSettings: (id: string) => `/jobs/${id}/settings`,
  jobsNew: "/jobs/new",
  candidates: "/candidates",
  candidate: (id: string) => `/candidates/${id}`,
  applicants: "/applicants",
  applicant: (id: string) => `/applicants/${id}`,
  interviews: "/interviews",
  interview: (id: string) => `/interviews/${id}`,
  interviewsWorkflow: (jobId: string) => `/interviews/workflow/${jobId}`,
  interviewIntelligence: "/interviews/intelligence",
  assessments: "/assessments",
  assessment: (id: string) => `/assessments/${id}`,
  schedules: "/schedules",
  scheduleAssessment: (assessmentId: string) => `/schedules/${assessmentId}`,
  scheduleScheduledDetail: (scheduleId: string) => `/schedules/scheduled/${scheduleId}`,
  mySchedule: "/my-schedule",
  questionPool: "/question-pool",
  questionPoolCreate: (type: string) => `/question-pool/create/${type}`,
  reports: "/reports",
  analytics: "/analytics",
  enterprises: "/enterprises",
  compare: "/compare",
  roles: "/roles",
  role: (id: string) => `/roles/${id}`,
  settings: "/settings",
  settingsEnterprises: "/settings/enterprises",
  settingsLocalization: "/settings/localization",
  settingsMigration: "/settings/migration",
  settingsEnterprise: "/settings/enterprise",
  settingsMyEnterprise: "/settings/my-enterprise",
  settingsMyProfile: "/settings/my-profile",
  settingsTeams: "/settings/teams",
  settingsProfile: "/settings/profile",
  settingsAppearance: "/settings/appearance",
  settingsNotifications: "/settings/notifications",
  settingsAudit: "/settings/audit",
  usersRoles: "/users-roles",
  /** @deprecated Use settingsMigration */
  migrations: "/migrations",
  /** @deprecated Use settingsLocalization */
  localization: "/localization",
  meet: "/meet",
  meetRoom: (roomId: string) => `/meet/${roomId}`,
} as const;
