#!/usr/bin/env node
/**
 * Storybook launcher for projects whose folder name contains "[" (e.g. Ze[code] 3.0).
 * Brackets break globs for config discovery and story path matching.
 *
 * - Symlink project → $TMPDIR/zecode-storybook-root (no "[" in paths)
 * - Temp config dir (no "[" in config path) so main.* discovery works
 * - Story directory uses the symlink path so index paths match ./src/...
 */
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const linkRoot = path.join(os.tmpdir(), "zecode-storybook-root");
const port = process.env.STORYBOOK_PORT ?? "6006";
const isBuild = process.argv.includes("--build");
const tmpConfig = fs.mkdtempSync(path.join(os.tmpdir(), "zecode-storybook-cfg-"));

const requireFromRoot = createRequire(path.join(root, "package.json"));

function ensureSymlink() {
  try {
    const stat = fs.lstatSync(linkRoot);
    if (stat.isSymbolicLink() && path.resolve(fs.readlinkSync(linkRoot)) === root) return;
    fs.rmSync(linkRoot, { recursive: true, force: true });
  } catch {
    /* missing */
  }
  fs.symlinkSync(root, linkRoot);
}

function resolveAddon(pkg) {
  try {
    return path.dirname(requireFromRoot.resolve(`${pkg}/package.json`));
  } catch {
    console.warn(`[storybook] Optional addon not installed: ${pkg}`);
    return null;
  }
}

function resolveNextConfig() {
  for (const name of ["next.config.ts", "next.config.mjs", "next.config.js"]) {
    const candidate = path.join(linkRoot, name);
    if (fs.existsSync(candidate)) return candidate.replace(/\\/g, "/");
  }
  return path.join(linkRoot, "next.config.js").replace(/\\/g, "/");
}

ensureSymlink();

const addons = ["@storybook/addon-docs", "@storybook/addon-a11y"]
  .map(resolveAddon)
  .filter(Boolean);

const storyDir = path.join(linkRoot, "src").replace(/\\/g, "/");
const publicDir = path.join(linkRoot, "public").replace(/\\/g, "/");
const globalsCss = path.join(linkRoot, "src/app/globals.css").replace(/\\/g, "/");
const aliasSrc = path.join(linkRoot, "src").replace(/\\/g, "/");
const aliasData = path.join(linkRoot, "data").replace(/\\/g, "/");
const linkModules = path.join(linkRoot, "node_modules").replace(/\\/g, "/");
const projectPreview = path.join(linkRoot, ".storybook", "preview.tsx");
const nextConfigPath = resolveNextConfig();

fs.writeFileSync(
  path.join(tmpConfig, "main.mjs"),
  `/** Generated by scripts/storybook-dev.mjs */
/** @type { import('@storybook/nextjs').StorybookConfig } */
const config = {
  stories: [
    {
      directory: ${JSON.stringify(storyDir)},
      files: '**/*.stories.@(ts|tsx)',
    },
  ],
  addons: ${JSON.stringify(addons)},
  framework: {
    name: '@storybook/nextjs',
    options: {
      nextConfigPath: ${JSON.stringify(nextConfigPath)},
    },
  },
  staticDirs: [${JSON.stringify(publicDir)}],
  webpackFinal: async (config) => {
    const cssPath = ${JSON.stringify(globalsCss)};
    const prependGlobalStyles = (entry) => {
      if (typeof entry === 'string') return [cssPath, entry];
      if (Array.isArray(entry)) return [cssPath, ...entry];
      if (entry && typeof entry === 'object') {
        const next = { ...entry };
        for (const key of Object.keys(next)) {
          next[key] = prependGlobalStyles(next[key]);
        }
        return next;
      }
      return entry;
    };
    config.entry = prependGlobalStyles(config.entry);
    config.resolve = config.resolve ?? {};
    config.resolve.alias = {
      ...(config.resolve.alias ?? {}),
      '@/data': ${JSON.stringify(aliasData)},
      '@': ${JSON.stringify(aliasSrc)},
    };
    config.resolve.modules = [
      ${JSON.stringify(linkModules)},
      ...(config.resolve.modules ?? ['node_modules']),
    ];
    config.watchOptions = {
      ...(config.watchOptions ?? {}),
      followSymlinks: true,
      ignored: /node_modules/,
      // Bracket paths + symlinks: poll so edits in the real project folder hot-reload
      poll: 1000,
    };
    return config;
  },
};

export default config;
`,
);

try {
  fs.symlinkSync(projectPreview, path.join(tmpConfig, "preview.tsx"));
} catch (err) {
  console.error("[storybook] Could not link preview.tsx:", err.message);
  process.exit(1);
}

const args = isBuild
  ? ["storybook", "build", "-c", tmpConfig, "--ci", "-o", "storybook-static"]
  : ["storybook", "dev", "-p", port, "-c", tmpConfig, "--ci"];

if (!isBuild && process.env.STORYBOOK_NO_OPEN === "1") args.push("--no-open");

const child = spawn(process.platform === "win32" ? "npx.cmd" : "npx", args, {
  cwd: linkRoot,
  stdio: "inherit",
  env: { ...process.env, STORYBOOK_DISABLE_TELEMETRY: "1" },
});

const cleanup = () => {
  try {
    fs.rmSync(tmpConfig, { recursive: true, force: true });
  } catch {
    /* ignore */
  }
  try {
    fs.rmSync(linkRoot, { recursive: true, force: true });
  } catch {
    /* ignore */
  }
};

child.on("exit", (code) => {
  cleanup();
  process.exit(code ?? 1);
});

process.on("SIGINT", () => child.kill("SIGINT"));
process.on("SIGTERM", () => child.kill("SIGTERM"));

console.log("Storybook (bracket-safe launcher)");
console.log(`  Symlink:  ${linkRoot}`);
console.log(`  Config:   ${tmpConfig}`);
console.log(`  Stories:  ${storyDir}`);
if (addons.length === 0) console.warn("  Addons:   none resolved — run npm install");
else console.log(`  Addons:   ${addons.length}`);
console.log(isBuild ? "  Output:   storybook-static/" : `  URL:      http://localhost:${port}`);
